services:
  freeradius:
    build: .
    container_name: freeradius
    restart: unless-stopped
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    volumes:
      - ./raddb:/etc/freeradius/3.0
    environment:
      ERP_URL: https://erp.yourcollege.edu
      RADIUS_SECRET: pass